eureka:
  client:
    eurekaServiceUrlPollIntervalSeconds: 10
    instanceInfoReplicationIntervalSeconds: 10
  instance:
    leaseExpirationDurationInSeconds: 10
    leaseRenewalIntervalInSeconds: 10
    hostname: ${HOSTNAME:localhost}.int.adeo.com
    instanceId: ${spring.cloud.client.hostname}:${server.port}
    preferIpAddress: ${REGISTER_WITH_IP:false}
spring:
  mvc:
    static-path-pattern: /swagger-ui.html
    locale: en_GB
    locale-resolver: fixed
management:
  health:
    vault:
      enabled: false
  endpoint:
    restart:
      # required for pause / resume endpoints
      enabled: true
    resume:
      enabled: true
    pause:
      enabled: true
    health:
      show-details: ALWAYS
    hystrix:
      stream:
        enabled: false
    # metrics-prometheus integration
    metrics:
      enabled: false
    prometheus:
      enabled: true
  endpoints:
    web:
      base-path: "/"
      exposure:
        include: "*"
      path-mapping:
        health: actuator/health
        info: actuator/info
        pause: actuator/pause
        prometheus: metrics
        restart: actuator/restart
        resume: actuator/resume
logbook:
  exclude:
    - /health
    - /actuator/health
    - /v2/api-docs
    - /swagger-ui.html
    - /null/**
    - /admin/**
    - /webjars/**
    - /swagger-resources/**
    - /metrics/**
    - /metrics.json/**
    - /hystrix.stream
    - /logfile
    - /logfile.json
  filter.enabled: true
  obfuscate:
    headers:
      - Authorization
      - X-Secret
      - X-Config-Token
    parameters:
      - access_token
      - password
  write:
    category: http.wire-log
    level: INFO
logging:
  level:
    ROOT: INFO
    com.netflix.discovery.shared.resolver.aws: WARN
    org.zalando.logbook.Logbook: TRACE
internalSystem:
  default:
    readTimeout: 35000
    connectTimeout: 5000
    maxConnPerRoute: 50
    maxConnTotal: 100

externalSystem:
  default:
    readTimeout: 30000
    connectTimeout: 10000
    maxConnPerRoute: 50
    maxConnTotal: 100
